### PR TITLE
Fix number of expected value returned by env.step()

### PR DESCRIPTION
**Pull request by rogierz**
When running `python test_random_policy.py` the following error occurs:

```
Traceback (most recent call last):
  File "test_random_policy.py", line 46, in <module>
    main()
  File "test_random_policy.py", line 35, in main
    state, reward, done, info = env.step(action)  # Step the simulator to the next timestep
  File "/home/user/aml22-rl/.venv/lib/python3.8/site-packages/gym/wrappers/time_limit.py", line 50, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
ValueError: not enough values to unpack (expected 5, got 4)
```

This is due to the number of values returned by `CustomHopper.step` method. This pull request fixes the issue and now `python test_random_policy.py` runs without errors.

### CODE REVIEW

**Comment by rogierz** [comment]
Actually, this fix doesn't work when trying to run a policy with `stable-baselines3`, so I'm closing the pull request.
Still `train_random_policy.py` doesn't work.

**Comment by gabrieletiboni** [comment]
Which version of `gym` are you using? You may check it out by executing `pip freeze | grep gym`.

I suspect you're using a version >= 0.26.x

Thank you for pointing that out, we'll have to use a version below 0.26 to make sure the APIs follow the "old" standards (env.step() returning 4 values instead of 5) in order to be compatible with stable-baselines3.

Let me know if it works by downgrading gym to, e.g. 0.25.2. You may check all releases [here](https://github.com/openai/gym/releases)

**Comment by gabrieletiboni** [comment]
Actually, @rogierz try downgrading gym to 0.21 which is the one I've been using to test the template. That one should also be the version required by stable-baselines3.

**Comment by rogierz** [comment]
I can confirm that after downgrading to `gym==0.21` everything works as expected.

**Comment by gabrieletiboni** [comment]
Great! I'm closing the pull request and will update the requirements.txt file to make sure gym==0.21 is installed as a dependency.

**Pull request closed without merging**
